### ISSUE TITLE
'wmic' Command is deprecated and may show undefined behaviour

### ISSUE THREAD

**Issue by ArthurHNL** [sindresorhus/windows-release#14]
The `wmic` command has been deprecated:

![image](https://user-images.githubusercontent.com/31919595/74105670-3f599300-4b60-11ea-9554-859064b9d788.png)

This means that it can break or otherwise show undefined behaviour when it is executed. For me, this has already happened when enabling Windows Credential Guard. In that case, `wmic os get caption` would always return an 'unspecified error' and a non-zero exit code.

The following command is not deprecated and produces the exact same output: `powershell (Get-CimInstance -Class Win32_OperatingSystem).Caption`. I would suggest replacing the call to `wmic os get caption` with this command.

**Comment by sindresorhus** [comment]
We have explored other options than `wmic` in the past: https://github.com/sindresorhus/windows-release/pull/11

// @MarkTiedemann

**Comment by MarkTiedemann** [comment]
```powershell
powershell (Get-CimInstance -Class Win32_OperatingSystem).Caption
```
sounds good to me.

Note that the result of this command is used to distinguish between Server and Client versions of Windows.

I explored doing this with a [native addon](https://github.com/MarkTiedemann/is-windows-server/blob/master/src/addon.cc) (including [fallbacks](https://github.com/MarkTiedemann/is-windows-server/blob/master/index.js)) here https://github.com/MarkTiedemann/is-windows-server if anyone is interested in improving this part.

I may get around to working on this topic again in the upcoming weeks (but I can't promise it).

**Comment by landsfiskalen** [comment]
I created a pull request for this. I just changed 

`const stdout = execa.sync('wmic', ['os', 'get', 'Caption']).stdout || '';`

to

`const stdout = execa.sync('powershell', ['(Get-CimInstance -ClassName Win32_OperatingSystem).caption']).stdout || '';`

I hope that should be enough. Got it working here at least.

**Comment by landsfiskalen** [comment]
Made a stupid mistake, in the latest commit to the pull request I added a check to see if WMIC is installed (try catch), if not user powershell. That way it still works on older OS:es using wmic.

So the code now looks like this:
`		let stdout;
		try {
			stdout = execa.sync('wmic', ['os', 'get', 'Caption']).stdout || '';
		} catch (error) {
			stdout = execa.sync('powershell', ['(Get-CimInstance -ClassName Win32_OperatingSystem).caption']).stdout || '';
		}`

**Comment by OfficialFreak** [comment]
The Powershell Fallback doesn't work because the powershell command does not exist on Windows and it throws an error. (Error message in German)

```
C:\Users\user\AppData\Roaming\npm\node_modules\yo\node_modules\execa\index.js:347
                throw err;
                ^

Error: Command failed: powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption
Der Befehl "powershell" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.


    at makeError (C:\Users\user\AppData\Roaming\npm\node_modules\yo\node_modules\execa\index.js:174:9)
    at Function.module.exports.sync (C:\Users\user\AppData\Roaming\npm\node_modules\yo\node_modules\execa\index.js:338:15)
    at windowsRelease (C:\Users\user\AppData\Roaming\npm\node_modules\yo\node_modules\windows-release\index.js:39:19)
    at osName (C:\Users\user\AppData\Roaming\npm\node_modules\yo\node_modules\os-name\index.js:39:18)
    at new Insight (C:\Users\user\AppData\Roaming\npm\node_modules\yo\node_modules\insight\lib\index.js:37:13)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\yo\lib\cli.js:54:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 1,
  stdout: '',
  stderr: 'Der Befehl "powershell" ist entweder falsch geschrieben oder\r\n' +
    'konnte nicht gefunden werden.\r\n',
  failed: true,
  signal: null,
  cmd: 'powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption',
  timedOut: false
}```

**Comment by MarkTiedemann** [comment]
@OfficialFreak `powershell` is available on Windows by default. Perhaps your `Path` is broken.

**Comment by ArthurHNL** [comment]
Everyone on https://github.com/apache/cordova-cli/issues/434 tried to work around the root issue by adjusting their `Path`, I'm guessing the irony isn't lost :)
