### ISSUE TITLE
Hangs when running v3.3 on Windows Server 2012 R2

### ISSUE THREAD

**Issue by rikbrowning** [sindresorhus/windows-release#17]
When I try a to run `windows-release` on our build machine it simply hangs and never returns anything.

Running the powershell command directly as the same user it gives me:
```
Microsoft Windows Server 2012 R2 Standard
```
When I roll back to version 3.2 I don't get any issue as it isn't using the powershell command.

Any ideas what might be causing the hang?

**Comment by sindresorhus** [comment]
// @landsfiskalen

**Comment by landsfiskalen** [comment]
Added a new pull request. See if that makes it more compatible with 3.2.
