### ISSUE TITLE
Server detection only on omitted arg? 

### ISSUE THREAD

**Issue by muntact** [sindresorhus/windows-release#8]
Hey it looks like windows server detection is supported now, but for some reason this code path is only executed if the release number is omitted: 

> Note: Most Windows Server versions cannot be detected based on the release number alone. There is runtime detection in place to work around this, but it will only be used if no argument is supplied.

Could you elaborate on the reasoning behind this behaviour, as this doesn't work with the upstream usage in os-names:
https://github.com/sindresorhus/os-name/blob/master/index.js#L28

Should an issue be opened against os-names to fix this, or should this be fixed in the win-release package?

**Comment by sindresorhus** [comment]
We could add a tweak here so that if the passed `release` equals `os.release()` we do the runtime detection.

@silverwind Thoughts?

**Comment by silverwind** [comment]
Fine with me. Just make sure that this behaviour is documented.
